export type classesType =
  | 'Artificer'
  | 'Barbarian'
  | 'Bard'
  | 'Cleric'
  | 'Druid'
  | 'Fighter'
  | 'Monk'
  | 'Paladin'
  | 'Ranger'
  | 'Rogue'
  | 'Sorcerer'
  | 'Warlock'
  | 'Wizard'

export type subClassesType =
  | 'Alchemist'
  | 'Armorer'
  | 'Artillerist'
  | 'Battle Smith'
  | 'Path of Berzerker'
  | 'Path of the Ancestral Guardian'
  | 'Path of the Beast'
  | 'Path of the Storm Herald'
  | 'Path of the Totem Warrior'
  | 'Path of the Zealot'
  | 'Path of Wild Magic'
  | 'College of Creation'
  | 'College of Eloquence'
  | 'College of Glamour'
  | 'College of Lore'
  | 'College of Swords'
  | 'College of Valor'
  | 'College of Whispers'
  | 'Domain of Knowledge'
  | 'Domain of Life'
  | 'Domain of Light'
  | 'Domain of Nature'
  | 'Domain of Order'
  | 'Domain of Peace'
  | 'Domain of Tempest'
  | 'Domain of the Forge'
  | 'Domain of the Grave'
  | 'Domain of Trickery'
  | 'Domain of Twilight'
  | 'Domain of War'
  | 'Circle of Dreams'
  | 'Circle of Land'
  | 'Circle of Moon'
  | 'Circle of Spores'
  | 'Circle of Stars'
  | 'Circle of the Shepard'
  | 'Circle of Wildfire'
  | 'Arcane Archer'
  | 'Battle Master'
  | 'Cavalier'
  | 'Champion'
  | 'Eldritch Knight'
  | 'Psi Warrior'
  | 'Rune Knight'
  | 'Samurai'
  | 'Way of Mercy'
  | 'Way of the Astral Self'
  | 'Way of the Drunken Master'
  | 'Way of the Four Elements'
  | 'Way of the Kensei'
  | 'Way of the Open Hand'
  | 'Way of the Shadow'
  | 'Way of the Sun Soul'
  | 'Oath of Conquest'
  | 'Oath of Devotion'
  | 'Oath of Glory'
  | 'Oath of Redemption'
  | 'Oath of the Ancients'
  | 'Oath of the Watchers'
  | 'Oath of Vengeance'
  | 'Beast Master'
  | 'Fey Wanderer'
  | 'Gloomstalker'
  | 'Horizon Walker'
  | 'Hunter'
  | 'Monster Slayer'
  | 'Swarmkeeper'
  | 'Arcane Trickster'
  | 'Assassin'
  | 'Inquisitive'
  | 'Mastermind'
  | 'Phantom'
  | 'Scout'
  | 'Soulknife'
  | 'Swashbuckler'
  | 'Thief'
  | 'Draconic Bloodline'
  | 'Wild Magic'
  | 'Divine Soul'
  | 'Shadow Magic'
  | 'Storm Sorcery'
  | 'Aberrant Mind'
  | 'Clockwork Soul'
  | 'The Archfey'
  | 'The Fiend'
  | 'The Great Old One'
  | 'The Celestial'
  | 'The Hexblade'
  | 'The Fathomless'
  | 'The Genie'
  | 'School of Abjuration'
  | 'School of Conjuration'
  | 'School of Divination'
  | 'School of Enchantment'
  | 'School of Evocation'
  | 'School of Illusion'
  | 'School of Necromancy'
  | 'School of Transmutation'
  | 'War Magic'
  | 'Bladesinging'
  | 'Order of Scribes'
