export type weaponsType =
  | 'club'
  | 'dagger'
  | 'greatclub'
  | 'handaxe'
  | 'javelin'
  | 'light hammer'
  | 'mace'
  | 'quarterstaff'
  | 'sickle'
  | 'spear'
  | 'unarmed strike'
  | 'crossbow, light'
  | 'dart'
  | 'shortbow'
  | 'sling'
  | 'battleaxe'
  | 'flail'
  | 'glaive'
  | 'greataxe'
  | 'greatsword'
  | 'halberd'
  | 'lance'
  | 'longsword'
  | 'maul'
  | 'morningstar'
  | 'pike'
  | 'rapier'
  | 'scimitar'
  | 'shortsword'
  | 'trident'
  | 'war pick'
  | 'warhammer'
  | 'whip'
  | 'blowgun'
  | 'crossbow, hand'
  | 'crossbow, heavy'
  | 'longbow'
  | 'net'

export type armorType = 'light' | 'medium' | 'heavy' | 'shield'
