export type racesType =
  | 'aasimar'
  | 'dragonborn'
  | 'dwarf'
  | 'elf'
  | 'firbolg'
  | 'gnome'
  | 'goliath'
  | 'half-elf'
  | 'half-orc'
  | 'halfling'
  | 'human'
  | 'kenku'
  | 'lizardfolk'
  | 'tabaxi'
  | 'tiefling'
  | 'triton'

export type subraceType =
  | 'protector aasimar'
  | 'scourge aasimar'
  | 'fallen aasimar'
  | 'hill dwarf'
  | 'mountain dwarf'
  | 'duergar'
  | 'high elf'
  | 'wood elf'
  | 'drow'
  | 'stout halfling'
  | 'lightfoot halfling'
  | 'variant human'
  | 'black dragon'
  | 'blue dragon'
  | 'brass dragon'
  | 'bronze dragon'
  | 'copper dragon'
  | 'gold dragon'
  | 'green dragon'
  | 'red dragon'
  | 'silver dragon'
  | 'white dragon'
  | 'forest gnome'
  | 'rock gnome'
